### PR TITLE
Fix for NoSuchMethodError: JSONObject.wrap.

### PR DESCRIPTION
**Pull request by nvazquezg**
Fix for java.lang.NoSuchMethodError: org.json.JSONObject.wrap when using the plugin with API < 19.

Apps using this plugin with API level < 19 will fail because org.json.JSONObject.wrap is only available in API >= 19. This is the error:

> java.lang.NoSuchMethodError: org.json.JSONObject.wrap
> 	at io.ionic.links.IonicDeeplink._bundleToJson(IonicDeeplink.java:139)
> 	at io.ionic.links.IonicDeeplink.handleIntent(IonicDeeplink.java:68)

This branch includes the source code for the missing function extracted from The Android Open Source Project: [org.json.JSONObject.java](https://android.googlesource.com/platform/libcore/+/310eafdfeb5db23a4d5e405bbe607cffd1f4b24a/json/src/main/java/org/json/JSONObject.java)

### CODE REVIEW

**Comment by mlynch** [comment]
Is there a different way? I'd rather not add this into the library and Ionic proper will soon be dropping support for Android < 4.4 as it's quickly losing market share.

**Comment by nvazquezg** [comment]
I don't like it either, but i need it to support 4.1+ devices. With libraries like Crosswalk we can support Android < 4.1 a bit longer. Today, Android 4.1-4.4 are 35% of my users.
Maybe you can specify in the README that this plugin requires Android 4.4 or newer so no one looses time with this problem.

**Comment by naveedahmed1** [comment]
Is it possible to prevent app crash on older devices due to this error?

**Comment by Manduro** [comment]
@nvazquezg This still crashes on Android.
```
E/AndroidRuntime(12863): FATAL EXCEPTION: main
E/AndroidRuntime(12863): java.lang.NoSuchMethodError: org.json.JSONArray.<init>
E/AndroidRuntime(12863): 	at io.ionic.links.IonicDeeplink._wrap(IonicDeeplink.java:173)
E/AndroidRuntime(12863): 	at io.ionic.links.IonicDeeplink._bundleToJson(IonicDeeplink.java:151)
E/AndroidRuntime(12863): 	at io.ionic.links.IonicDeeplink.handleIntent(IonicDeeplink.java:70)
E/AndroidRuntime(12863): 	at io.ionic.links.IonicDeeplink.onNewIntent(IonicDeeplink.java:61)
E/AndroidRuntime(12863): 	at org.apache.cordova.PluginManager.onNewIntent(PluginManager.java:327)
E/AndroidRuntime(12863): 	at org.apache.cordova.CordovaWebViewImpl.onNewIntent(CordovaWebViewImpl.java:422)
E/AndroidRuntime(12863): 	at org.apache.cordova.CordovaActivity.onNewIntent(CordovaActivity.java:257)
E/AndroidRuntime(12863): 	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1205)
E/AndroidRuntime(12863): 	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2467)
E/AndroidRuntime(12863): 	at android.app.ActivityThread.performNewIntents(ActivityThread.java:2492)
E/AndroidRuntime(12863): 	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2501)
E/AndroidRuntime(12863): 	at android.app.ActivityThread.access$1400(ActivityThread.java:151)
E/AndroidRuntime(12863): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412)
E/AndroidRuntime(12863): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(12863): 	at android.os.Looper.loop(Looper.java:155)
E/AndroidRuntime(12863): 	at android.app.ActivityThread.main(ActivityThread.java:5454)
E/AndroidRuntime(12863): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(12863): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(12863): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
E/AndroidRuntime(12863): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)
E/AndroidRuntime(12863): 	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by nvazquezg** [comment]
@Manduro, it should work, org.json.JSONArray was added in API 1: https://developer.android.com/reference/org/json/JSONArray.html

I've had no more crashes since this fix. What is your Android version?

**Comment by Manduro** [comment]
@nvazquezg I noticed that too, but it doesn't. Testing on 4.1.1.

**Comment by nvazquezg** [comment]
@Manduro, I would try with an empty app to see if there is any clue. I don't have any 4.1.1 device to test, but I have about 600 users with Android 4.1 and no errors registered. I'm compiling with [crosswalk ](https://crosswalk-project.org/documentation/cordova.html) for those devices.

**Comment by mlynch** [comment]
Hey, had a change of heart, don't need to see you all struggle w/ this. Thanks for the PR and please try master with this merge and let me know how it works! Thanks for the help

**Comment by Manduro** [comment]
Great :)

@nvazquezg No clue unfortunately. I'm compiling with crosswalk as well. It errors on a certain `wraporg.chromium.chrome.browser.user_gesture_token` that is passed from Chrome in intent's extras. It's value is logged (`String.valueOf(o)`) as `[B@422a7c38` before `return new JSONArray(o);`.

I'm using a `return null;` there now to get it to work.

**Comment by nvazquezg** [comment]
@Manduro, unfortunatelly I confirm your issue in some android 4.2 and 4.3 devices. Maybe you can do another PR with your workaround... I'll be happy to test it.

**Comment by Manduro** [comment]
@nvazquezg You can find my workaround here: https://github.com/Manduro/ionic-plugin-deeplinks/commit/4779bc59902e8c8f80cf2df59ec45a4a61d2e4f1. Let's be clear it's not a fix but a workaround as it removes that small bit of functionality.

**Pull request merged**
