### PR TITLE
#99: Fix Xcode project file detection for Cordova 7

### PR DESCRIPTION
**Pull request by peterpeterparker**
Hi,

Here's my quick and dirty pull request to solve the Xcode project file detection after the upgrade to Cordova 7.

Best regards

### CODE REVIEW

**Comment by kevin-lot** [comment]
Hi,

I cannot get the good/last version with npm, yarn or cordova. Can you bump version plz ?
Or I have to wait still for a while ?

Best regards.

**Comment by Maziar-Fotouhi** [comment]
@mlynch Could you please do a version bump for this?
Thanks.

**Comment by mlynch** [comment]
Will do a bump. For future reference: you can always install directly from an npm repo: `cordova plugin add https://github.com/driftyco/ionic-plugin-deeplinks`

**Comment by mlynch** [comment]
Okay just published 1.0.15 to npm

**Pull request merged**
