### PR TITLE
Ios generate associated domains

### LINKED ISSUE #7: Generate X-Code Project Entitlements File
**Feature Request**

One thing that `cordova-universal-links-plugin` would do is generate the Entitlements file for X-Code.  Automating this step removes a manual step that would otherwise be required for deploying to iOS. 

Browsing through `cordova-universal-links-plugin`, it looks like this is the point in their code which generates the [entitlement file](https://github.com/nordnet/cordova-universal-links-plugin/blob/master/hooks/afterPrepareHook.js#L71)

It's been quite some time since I've used any cloud-compiler service for cordova projects, but automating this step may be necessary to enable the feature for some projects.  You guys probably have a better idea of that though.

### PR DESCRIPTION
**Pull request by mvidailhet**
This code will automatically generate and activate the iOS associated domains. This should resolve #7
- Generates entitlements file for the iOS app.
- Automatically activates associated domains in Xcode project and adds the DEEPLINK_HOST as an applink.

### CODE REVIEW

**Comment by mlynch** [comment]
Hey @mvidailhet, where does it place the file that it generates? That was one issue I had with the universal links plugin, it's naming and file placement left something to be desired

**Comment by mvidailhet** [comment]
hey @mlynch, it creates the file in platforms/ios/[app_name]/Resources/[app_name].entitlements

**Comment by georgedrummond** [comment]
@mlynch is this file location good? If we need any changes to get this merged I'd love to help out.

**Comment by mlynch** [comment]
Sure that works, thanks!

**Comment by mlynch** [comment]
Reverting this for now since we ran into some issues, will come back to this

**Comment by towicode** [comment]
Did this ever get re-merged into the feature, or do you still have to do this manually in xcode?

**Comment by dwieeb** [comment]
Leaving a note that iOS builds in Ionic Package are not working with ionic-plugin-deeplinks plugin. See https://github.com/driftyco/ionic-cloud/issues/112

**Comment by mlynch** [comment]
Okay I just brought those commits back in and added some protections. Can you guys try master and see if it's working now?

@mvidailhet there's no documentation on how the user should use those hooks, any chance you can fill in more info?

**Comment by mvidailhet** [comment]
@mlynch sorry for the wait. I'm happy to help!

Well it actually removes the steps we had to do manually in xcode to configure Universal Links:
- Generates entitlements file for the iOS app.
- Automatically activates associated domains in Xcode project and adds the DEEPLINK_HOST as an applink.

It's the step "Configuring Universal Links (iOS) and App Links (Android)" in your Blog post on [Deeplinking in Ionic Apps](http://blog.ionic.io/deeplinking-in-ionic-apps/)

**Pull request merged**
